// This is a Declarative Jenkinsfile to be used in the homework
// It should map very well to what you learned in class.
// Implement the sections marked with "TBD:"


pipeline {
  agent {
    kubernetes {
      label "maven-skopeo-agent"
      cloud "openshift"
      inheritFrom "maven"
      containerTemplate {
        name "jnlp"
        image "image-registry.openshift-image-registry.svc:5000/${GUID}-jenkins/jenkins-agent-appdev:latest"
        resourceRequestMemory "2Gi"
        resourceLimitMemory "2Gi"
        resourceRequestCpu "2"
        resourceLimitCpu "2"
      }
    }
  }
  environment { 
    // Define global variables
    // Set Maven command to always include Nexus Settings
    // NOTE: Somehow an inline pod template in a declarative pipeline
    //       needs the "scl_enable" before calling maven.
    def jenkinsBuildNumber = "${env.BUILD_NUMBER}"
    mvnCmd = "source /usr/local/bin/scl_enable && mvn -s ./nexus_settings.xml"

    // Images and Projects
    imageName   = "${GUID}-tasks"
    devProject  = "${GUID}-tasks-dev"
    prodProject = "${GUID}-tasks-prod"

    // Tags
    devTag      = "0.0-0"
    prodTag     = "0.0"
    
    // Blue-Green Settings
    destApp     = "tasks-green"
    activeApp   = ""
  }
  stages {

    stage('Print Vars') {
      steps {
        echo "Print Vars:  mvnCmd = ${mvnCmd} "
        echo "Print Vars:  devProject = ${devProject} "
        echo "Print Vars:  prodProject = ${prodProject} "
        echo "Print Vars:  jenkinsBuildNumber = ${jenkinsBuildNumber} "
        sh "mvn -v"
        sh "oc whoami"
      }
    }

    // Checkout Source Code.
    stage('Checkout Source') {
      steps {
        checkout scm

          script {
            def pom = readMavenPom file: 'pom.xml'
            def version = pom.version
            
            // Set the tag for the development image: version + build number
            devTag  = "${version}-" + currentBuild.number
            // Set the tag for the production image: version
            prodTag = "${version}"

            // Patch Source artifactId to include GUID
            sh "sed -i 's/GUID/${GUID}/g' ./pom.xml"
          }
      }
    }

    // Build the Tasks Application in the directory 'openshift-tasks'
    stage('Build war') {
      steps {
          script {
            echo "Building version ${devTag}"

            //TBD: Execute the Maven Build

          }
      }
    }

    // Using Maven run the unit tests
    stage('Unit Tests') {
      steps {
          echo "Running Unit Tests"

        // TBD: Execute Unit Tests

      }
    }
    // Using Maven call SonarQube for Code Analysis
    stage('Code Analysis') {
      steps {
          script {
            echo "Running Code Analysis"

            // TBD: Execute Sonarqube Tests
            //      Your project name should be "${GUID}-${JOB_BASE_NAME}-${devTag}"
            //      Your project version should be ${devTag}

          }
      }
    }
    // Publish the built war file to Nexus
    stage('Publish to Nexus') {
      steps {
          echo "Publish to Nexus"

          // TBD: Publish to Nexus

      }
    }
    // Build the OpenShift Image in OpenShift and tag it.
    stage('Build and Tag OpenShift Image') {
      steps {

          script {
            echo "Building OpenShift container image ${imageName}:${devTag} in project ${devProject}."
            // TBD: Build Image (binary build), tag Image
            //      Make sure the image name is correct in the tag!


          }
      }
    }
    // Deploy the built image to the Development Environment.
    stage('Deploy to Dev') {
      steps {
          script {
            echo "Deploying container image to Development Project"

            // TBD: Deploy to development Project
            //      Set Image, Set VERSION
            //      (Re-) Create ConfigMap
            //      Make sure the application is running and ready before proceeding

          }
      }
    }

    // Copy Image to Nexus Container Registry
    stage('Copy Image to Nexus Container Registry') {
      steps {
        script {
          echo "Copy image to Nexus Container Registry"

          // TBD: Copy image to Nexus container registry

          // TBD: Tag the built image with the production tag.

        }
      }
    }

    // Blue/Green Deployment into Production
    // -------------------------------------
    stage('Blue/Green Production Deployment') {
      steps {
        script {
          echo "Blue/Green Production Deployment"

          // TBD: Determine which application is active
          //      Set Image, Set VERSION
          //      (Re-)create ConfigMap
          //      Deploy into the other application
          //      Make sure the application is running and ready before proceeding

        }
      }
    }

    stage('Switch over to new Version') {
      steps{
        script {
          echo "Switching Production application to ${destApp}."
          // TBD: Execute switch
          //      Hint: sleep 5 seconds after the switch
          //            for the route to be fully switched over

        }
      }
    }
  }
}
